### ISSUE TITLE
Vulnerability in transitive library

### ISSUE THREAD

**Issue by prashantLio** [ALMaclaine/replace#11]
Hi
I have updated to latest replace i.e 1.1.1
It is using older yargs and it in turns uses older version of execa which is vulnerable.
Can you please share any details for  why we are using older yargs version or are there any plans to upgrade it.

**Comment by ALMaclaine** [comment]
Sorry, I merged in a PR to update yargs but didn't publish.

I published and when I install i get the new versions v1.1.2, as of this comment the npm page had not updated to reflect.

Please let me know if there are any other issues.
