### ISSUE TITLE
Single quotes omitted from output of replace in npm script

### ISSUE THREAD

**Issue by douglassboshkoff** [ALMaclaine/replace#14]
We were using version 1.1.1 of replace in our project in the following npm script.

`"replace:envConfigs": "replace '__APP_VERSION__' \"'$npm_package_version'\" ./dist/lib-esm -r --include='*.js'"`

We used this to fill in the application version in the following line of code. 
`const version = __APP_VERSION__;`

After updating to replace 1.1.3, our build broke. 

Output of replace 1.1.1
`var version = '0.1.11';`

Output of replace 1.1.3
`var version = 0.1.11;`

Is this a bug or user error? If a user error, how should we modify our build script.

**Comment by ALMaclaine** [comment]
I just pushed v1.1.4, i dont think it fixed it but will you try.

@dwarfess @goto-bus-stop do you know what happend here?

**Comment by ALMaclaine** [comment]
this looks a little weird to me though

`\"'$npm_package_version'\"`

why are you escaping the "

I don't have a strong opinion about what the "correct" usage should be, especially in cases like this. Open to opinions.

Maybe you can try `const version = '__APP_VERSION__';` in the mean time.

**Comment by goto-bus-stop** [comment]
looks like command line arguments handling changed—most likely cause would be https://github.com/ALMaclaine/replace/commit/1c320b0f4dcb649fbc883ac09e32c933199be3ca

**Comment by goto-bus-stop** [comment]
Probably caused by this change in yargs-parser v12 (used by yargs v13): https://github.com/yargs/yargs-parser/pull/153
This PR is supposed to address that: https://github.com/yargs/yargs-parser/pull/222

**Comment by goto-bus-stop** [comment]
I think the simplest solution is to downgrade for the time being: https://github.com/ALMaclaine/replace/pull/15

**Comment by ALMaclaine** [comment]
okay v1.1.5 is published

thank you everyone
