### ISSUE TITLE
nexus vulnerability issue with latest replace

### ISSUE THREAD

**Issue by prashantLio** [ALMaclaine/replace#17]
Hi,
I am using the latest replace version i.e 1.1.5. It has dependency of yargs which in turn calls yargs-parser. Your latest replace version uses older version of yargs which is vulnerable.

-- replace@1.1.5
  `-- yargs@12.0.5
    `-- yargs-parser@11.1.1

**Comment by prashantLio** [comment]
hi,
Any update on above issue, adding one more issue regarding execa
`-- replace@1.1.5
  `-- yargs@12.0.5
    `-- os-locale@3.1.0
      `-- execa@1.0.0

**Comment by ALMaclaine** [comment]
I've updated yargs but it's broken part of the API. please report any issues.
