### ISSUE TITLE
replace cannot work

### ISSUE THREAD

**Issue by 2010hexi** [ALMaclaine/replace#21]
i use search it is good
```
$ search     import.meta.url  index.html

index.html

 29:     import.meta.url

```
but when i use repalce
```
$ replace import.meta.url  aaa index.html

无效的开关 - index.html

未替换文件
```

**Comment by ALMaclaine** [comment]
The warnings in `replace` are written in English using the latin alphabet. You are getting back Chinese characters that according to google translate read `Invalid Switch`.

Please refer to this section of the README:
https://github.com/ALMaclaine/replace#common-issue-on-windows
