### ISSUE TITLE
Error: ENOENT: no such file or directory, lstat

### ISSUE THREAD

**Issue by coolvasanth** [ALMaclaine/replace#26]
Environment Information
Platform: Angular
Version: 11

**Purpose**: After production build generation, in project/dist/projectname/styles.c95f65c7eeb66e6c26e0.css file I need to replace word /asset with asset.

**Problem**: Replace package works fine when I give the exact file name, like below
**package.json file**
`"adjust-path":"replace '/assets' 'assets' 'dist/MyProjectName/styles.c95f65c7eeb66e6c26e0.css '", 

But here styles.c95f65c7eeb66e6c26e0.css is a dynamically generated file, So I need a regular expression to match the number - c95f65c7eeb66e6c26e0. 

So I wrote script like below 
`"adjust-path":"replace '/assets' 'assets' 'dist/MyProjectName/styles.*.css'",`

But is not matching the regular expression * and giving error no file or directory. 

Please let me know, what regular expression I need to use, thanks in advance, waiting for the response.

**Comment by ALMaclaine** [comment]
Hey just an fyi I inherited this package.

There appear to be some fundamental issues with the library from when it was created.

I'm going to look into re-writing replace and addressing these issues. I'm sorry but I don't have any immediate advice, I'll take these issues into consideration when re-writing.

**Comment by ALMaclaine** [comment]
@coolvasanth 

have you tried this pattern?

`replace 'foo' 'bar' . -r --include="*.js"`
