### ISSUE TITLE
Regex pipe escapes string

### ISSUE THREAD

**Issue by fdendorfer** [ALMaclaine/replace#27]
When using the command `npx replace '(href|src|\"href\"|\"src\")=\"/' '$1=\"../'` the output returns "'src' is not recognized as an internal or external command". If I escape each pipe the output is just "'src\' is not...". 
Any way to prevent this?

OS: Windows 10
Package version: 1.2.1

**Comment by ALMaclaine** [comment]
No I don't have any suggestions unfortunately. Additionally it's probably too late at this point in the packages life to change its internal API, the test cases generated at the outset of the package were not exhaustive enough to show any changes won't break something. It might could get resolved in a v2, but without sufficient community support both in terms of requests and test cases it probably isn't going to happen.
