### ISSUE TITLE
Stdin

### ISSUE THREAD

**Issue by a-x-** [ALMaclaine/replace#3]
Oo

stdin is must have...

**Comment by a-x-** [comment]
`echo "1\n2\n4" | replace '1\n2' ''`

**Comment by ALMaclaine** [comment]
Done. Needs -z flag.

`echo "asd" | replace "asd" "dsa" -z`

**Comment by a-x-** [comment]
Yay! Thank you

usually utilites uses `-` as a stdin-enable-flag (e.g. `echo 123 | cat -`), but that's not so critical

**Comment by ALMaclaine** [comment]
I don't think it's possible using yargs but I asked them, if so I will change, otherwise maybe in the future using something other than yargs.
