### ISSUE TITLE
Please Upgrade the "minimatch" dependency

### ISSUE THREAD

**Issue by ruettenm** [ALMaclaine/replace#32]
Hi,

could you change the change the version in your `package.json` from

`"minimatch": "3.0.4",`

to at least 

`"minimatch": "^3.0.4",`

I'm asking because **version 3.0.4 of minimatch** has a vulnerability
> https://github.com/advisories/GHSA-f8q6-p94x-37v3

**Comment by ALMaclaine** [comment]
Published 1.2.2

**Comment by inpercima** [comment]
Hi @ALMaclaine, thank you for your changes. You wrote you published 1.2.2 but I can not find it in npm. What can I do?

**Comment by ALMaclaine** [comment]
@inpercima my apologies, I had published this to my private npm registry.

It should be on npm now.

**Comment by inpercima** [comment]
Hey @ALMaclaine No problem. I can now find and load it. Thank you very much.
